# -*- coding: utf-8 -*-
"""
Read docs/page-copy workbooks and emit src/i18n/messages/pageCopyWorkbookOverrides.ts
for merge in translate + workbookResolve().

Reads: 01, 02, 03 (创始人故事), 04, 05, 06 (万有元神) under docs/page-copy/.
Optional: copies same patterns from the parent folder of the repo if present.

Run from repo root: python scripts/generate-page-copy-overrides.py
Requires: openpyxl
"""
from __future__ import annotations

import json
import os
import shutil
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    print("Install openpyxl: pip install openpyxl", file=sys.stderr)
    sys.exit(1)

SCRIPT = Path(__file__).resolve()
ROOT = SCRIPT.parent.parent
OUT_TS = ROOT / "src" / "i18n" / "messages" / "pageCopyWorkbookOverrides.ts"
PAGE_COPY = ROOT / "docs" / "page-copy"
# Local sheets folder (parent of cloned repo)
LOCAL_SITE = ROOT.parent

PATTERNS = ("01-*.xlsx", "02-*.xlsx", "03-*.xlsx", "04-*.xlsx", "05-*.xlsx", "06-*.xlsx")


def cell_str(v) -> str:
    if v is None:
        return ""
    if isinstance(v, float) and v == int(v):
        return str(int(v))
    return str(v).strip()


def copy_local_workbooks() -> None:
    """Optional: pull sheets from repo parent (e.g. I:\\网站\\). Off by default so docs/page-copy in-repo is not overwritten."""
    if os.environ.get("PAGE_COPY_PULL_PARENT", "").strip() not in ("1", "true", "yes"):
        return
    if not LOCAL_SITE.exists():
        return
    PAGE_COPY.mkdir(parents=True, exist_ok=True)
    for pat in PATTERNS:
        for src in sorted(LOCAL_SITE.glob(pat)):
            if src.name.startswith("~$"):
                continue
            dest = PAGE_COPY / src.name
            shutil.copy2(src, dest)
            print("Copied", src.name, "-> docs/page-copy/")


def read_workbook(path: Path) -> tuple[dict[str, str], dict[str, str]]:
    en_out: dict[str, str] = {}
    zh_out: dict[str, str] = {}
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb[wb.sheetnames[0]]
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row or not row[0]:
            continue
        key = cell_str(row[0])
        if not key:
            continue
        en = cell_str(row[3]) if len(row) > 3 else ""
        zh = cell_str(row[4]) if len(row) > 4 else ""
        if en:
            en_out[key] = en
        if zh:
            zh_out[key] = zh
    return en_out, zh_out


def main() -> None:
    copy_local_workbooks()
    merged_en: dict[str, str] = {}
    merged_zh: dict[str, str] = {}
    for pat in PATTERNS:
        for path in sorted(PAGE_COPY.glob(pat)):
            if path.name.startswith("~$"):
                continue
            en, zh = read_workbook(path)
            merged_en.update(en)
            merged_zh.update(zh)
            print("Read", path.name, "rows(en)", len(en), "rows(zh)", len(zh))

    # Stable key order for smaller diffs
    en_json = json.dumps(dict(sorted(merged_en.items())), ensure_ascii=False, indent=2)
    zh_json = json.dumps(dict(sorted(merged_zh.items())), ensure_ascii=False, indent=2)

    ts = f"""/**
 * AUTO-GENERATED by scripts/generate-page-copy-overrides.py
 * Do not edit by hand. Regenerate after updating docs/page-copy/01–06 (see generate-page-copy-overrides.py).
 */
export const pageCopyWorkbookEn: Record<string, string> = {en_json};

export const pageCopyWorkbookZh: Record<string, string> = {zh_json};
"""
    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.write_text(ts, encoding="utf-8")
    print("Wrote", OUT_TS.relative_to(ROOT), "keys en:", len(merged_en), "zh:", len(merged_zh))


if __name__ == "__main__":
    main()
